version: "3.9"
services:
  app:
    restart: unless-stopped
    build: visualizer/.
    ports:
      - "${VISUALIZER_APP_PORT:-5000}:5000"
    environment:
      DB_HOST: db
      DB_USERNAME: "${DB_USERNAME:-postgres}"
      DB_DATABASE: "${DB_DATABASE:-postgres}"
      DB_PASSWORD: "${DB_PASSWORD}"
    depends_on:
      - db
  db:
    build: db/.
    restart: unless-stopped
    ports:
     - "5432:5432" # FOR EDITOR APP - SHOULD BE ACCESSIBLE TO OTHER CONTAINERS WITHIN NETWORK
    environment: 
      POSTGRES_USER: "${DB_USERNAME:-postgres}"
      POSTGRES_DB:  "${DB_DATABASE:-postgres}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      PGDATA: /var/lib/postgresql/data
    volumes:
      - pg-data:/var/lib/postgresql/data
  db-admin:
    # https://www.pgadmin.org/docs/pgadmin4/latest/container_deployment.html
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  pg-data:
  pgadmin-data: