#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" \
  -c "CREATE USER $APP_DB_USER WITH PASSWORD '$APP_DB_PASSWORD';" \
  -c "GRANT CONNECT ON DATABASE $POSTGRES_DB TO $APP_DB_USER;" \
  -c "GRANT USAGE ON SCHEMA public TO $APP_DB_USER;" \
	-c "GRANT SELECT ON ALL TABLES IN SCHEMA public TO $APP_DB_USER;" \ 
  -c "ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO $APP_DB_USER;"